ROSTemplateFormatVersion: '2015-09-01'
Description:
  en: In the online education industry, most teachers are not located in the same
    region or country as the students. For example, in scenario-based online English
    education programs, the teachers are based in North America, while the students
    are from various regions in China. This template can be used together with the
    template for building a resource environment in a single region to complete network
    planning for global deployment.
  zh-cn: 在线教育的教师大部分和学员不在相同区域，设置不在同一个国家。例如场景的英语类在线教育，教师在北美，学员分布在国内各地区；此模板配合搭建单个地域的资源环境模板完成全球部署网络规划。
Conditions:
  IsCreateDomestic:
    Fn::Equals:
    - Ref: CenGeographicRegionBId
    - China
  IsCreateOversea:
    Fn::Not:
      Fn::Equals:
      - Ref: CenGeographicRegionBId
      - China
  IsCreateVbr:
    Fn::Not:
      Fn::Equals:
      - Ref: VbrId4Domestic
      - default
Parameters:
  ChildInstanceRegionId1:
    Type: String
    Label:
      en: Overseas VPC Instance Region
      zh-cn: 境外专有网络实例地域
    Description:
      en: The territory of an offshore proprietary network instance
      zh-cn: 境外专有网络实例所在的地域
    AllowedValues:
    - ap-south-1
    - eu-west-1
    - ap-northeast-1
    - me-east-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-southeast-3
    - eu-central-1
    - ap-southeast-5
    - us-east-1
    - us-west-1
    - cn-shenzhen
    - cn-beijing
    - cn-chengdu
    - cn-qingdao
    - cn-shanghai
    - cn-hongkong
    - cn-huhehaote
    - cn-zhangjiakou
    - cn-hangzhou
  VpcId1Overseas:
    Type: String
    Label:
      en: Overseas VPC Instance ID
      zh-cn: 境外专有网络实例ID
    Description:
      en: Existing offshore proprietary network instance ID, e.g., VPC instance ID,
        US(silicon valley).
      zh-cn: 已存在的境外专有网络实例ID，如： 美国（硅谷）VPC实例ID。
    MinLength: 3
  ChildInstanceRegionId2:
    Type: String
    Label:
      en: Domestic VPC 1 Instance Region
      zh-cn: 国内专有网络1实例地域
    Description:
      en: Domestic proprietary network 1 instance region
      zh-cn: 国内专有网络1实例地域
    AllowedValues:
    - cn-shenzhen
    - cn-beijing
    - cn-chengdu
    - cn-qingdao
    - cn-shanghai
    - cn-hongkong
    - cn-huhehaote
    - cn-zhangjiakou
    - cn-hangzhou
  VpcId2Domestic:
    Type: String
    Label:
      en: Domestic VPC 1 Instance ID
      zh-cn: 国内专有网络1实例ID
    Description:
      en: 'Existing domestic proprietary network instance ID, such as: hangzhou VPC
        instance ID.'
      zh-cn: 已存在的国内专有网络实例ID，如： 杭州VPC实例ID。
    MinLength: 3
  VbrId4Domestic:
    Type: String
    Label:
      en: Domestic Physical Special Line Instance ID
      zh-cn: 国内物理专线实例ID
    Description:
      en: 'Existing domestic physical special line instance ID, the physical special
        line and the domestic proprietary network 1 instance region is the same and
        the network segment can not be duplicated with other VPC network segment of
        the network;<font color=''blue''><br><b>Note: the network with the physical
        dedicated line will not be opened by default.</b><font>'
      zh-cn: 已存在的国内物理专线实例ID，该物理专线与国内专有网络1实例地域相同并且网段不能与组网的其他VPC网段重复; <font color='blue'><br><b>注：默认default时不打通与物理专线的网络。</b><font>
    Default: default
    MinLength: 3
  ChildInstanceRegionId3:
    Type: String
    Label:
      en: Domestic VPC 2 Instance Region
      zh-cn: 国内专有网络2实例地域
    Description:
      en: Domestic proprietary network 1 instance region
      zh-cn: 国内专有网络2实例地域
    AllowedValues:
    - cn-shenzhen
    - cn-beijing
    - cn-chengdu
    - cn-qingdao
    - cn-shanghai
    - cn-hongkong
    - cn-huhehaote
    - cn-zhangjiakou
    - cn-hangzhou
  VpcId3Domestic:
    Type: String
    Label:
      en: Domestic VPC 2 Instance ID
      zh-cn: 国内专有网络2实例ID
    Description:
      en: 'Existing domestic proprietary network instance ID, such as: beijing VPC
        instance Id.'
      zh-cn: 已存在的国内专有网络实例ID，如： 北京VPC实例ID。
    MinLength: 3
  CenGeographicRegionBId:
    Type: String
    Label:
      en: Overseas VPC Instance Area
      zh-cn: 境外专有网络实例所属大区
    Description:
      en: '<font color=''blue''><b>The overseas proprietary network instance belongs
        to the region，Purchasing a cross-border bandwidth pack requires that the current
        account be enterprise certified;<br>Optional values: </b></font><br>[China:
        <font color=''green''>China, Select this option not to create cross-border
        bandwidth packets</font>]<br>[North-America: <font color=''green''>North-America</font>]<br>[Asia-Pacific:
        <font color=''green''>Asia-Pacific</font>]<br>[Europe: <font color=''green''>Europe</font>]<br>[Australia:
        <font color=''green''>Australia</font>]<br><font color=''blue''></a>'
      zh-cn: '<font color=''blue''><b>境外专有网络实例所属大区，购买跨境带宽包需要保证当前帐号已取得企业认证;<br>可选值:
        </b></font><br>[China: <font color=''green''>中国大陆, 选择此项不创建跨境带宽包</font>]<br>[North-America:
        <font color=''green''>北美</font>]<br>[Asia-Pacific: <font color=''green''>亚太</font>]<br>[Europe:
        <font color=''green''>欧洲</font>]<br>[Australia: <font color=''green''>澳洲</font>]<br><font
        color=''blue''></a>'
    Default: China
    AllowedValues:
    - China
    - North-America
    - Asia-Pacific
    - Europe
    - Australia
  CenPricingCycle:
    Type: String
    Label:
      en: Outbound Bandwidth Packet Billing Cycle
      zh-cn: 境外带宽包计费周期
    Description:
      en: 'The billing cycle of the bandwidth packet outside the enterprise network.
        Value: Month | Year, the default value is Month.'
      zh-cn: 企业网境外带宽包的计费周期。取值：Month | Year，默认值为Month。
    Default: Month
    AllowedValues:
    - Month
    - Year
  CenBandwidth:
    Type: Number
    Label:
      en: Outbound Bandwidth Packet Bandwidth Peak
      zh-cn: 境外带宽包带宽峰值
    Description:
      en: The bandwidth peak of the bandwidth packet outside the enterprise network
        in Mbps and the minimum value is 3.
      zh-cn: 企业网境外带宽包的带宽峰值，单位为Mbps，最小值为3。
    Default: 5
    MinValue: 3
    MaxValue: 10000
Resources:
  CenBandwidthPackage1:
    Type: ALIYUN::CEN::CenBandwidthPackage
    Properties:
      Bandwidth:
        Ref: CenBandwidth
      BandwidthPackageChargeType: POSTPAY
      GeographicRegionAId: China
      GeographicRegionBId: China
  CenInstance:
    Type: ALIYUN::CEN::CenInstance
    Properties:
      Name:
        Fn::Join:
        - '-'
        - - StackId
          - Ref: ALIYUN::StackId
  CenInstanceAttachmentVbr4:
    Type: ALIYUN::CEN::CenInstanceAttachment
    Condition: IsCreateVbr
    Properties:
      CenId:
        Ref: CenInstance
      ChildInstanceId:
        Ref: VbrId4Domestic
      ChildInstanceRegionId:
        Ref: ChildInstanceRegionId2
      ChildInstanceType: VBR
  CenInstanceAttachmentVpc1:
    Type: ALIYUN::CEN::CenInstanceAttachment
    Properties:
      CenId:
        Ref: CenInstance
      ChildInstanceId:
        Ref: VpcId1Overseas
      ChildInstanceRegionId:
        Ref: ChildInstanceRegionId1
      ChildInstanceType: VPC
  CenInstanceAttachmentVpc2:
    Type: ALIYUN::CEN::CenInstanceAttachment
    Properties:
      CenId:
        Ref: CenInstance
      ChildInstanceId:
        Ref: VpcId2Domestic
      ChildInstanceRegionId:
        Ref: ChildInstanceRegionId2
      ChildInstanceType: VPC
  CenInstanceAttachmentVpc3:
    Type: ALIYUN::CEN::CenInstanceAttachment
    Properties:
      CenId:
        Ref: CenInstance
      ChildInstanceId:
        Ref: VpcId3Domestic
      ChildInstanceRegionId:
        Ref: ChildInstanceRegionId3
      ChildInstanceType: VPC
  CenBandwidthPackageAssociation1:
    Type: ALIYUN::CEN::CenBandwidthPackageAssociation
    Properties:
      CenBandwidthPackageId:
        Ref: CenBandwidthPackage1
      CenId:
        Ref: CenInstance
    DependsOn:
    - CenBandwidthPackage1
    - CenInstance
    - CenInstanceAttachmentVbr4
    - CenInstanceAttachmentVpc1
    - CenInstanceAttachmentVpc2
    - CenInstanceAttachmentVpc3
  CenBandwidthPackage2:
    Type: ALIYUN::CEN::CenBandwidthPackage
    Condition: IsCreateOversea
    Properties:
      AutoPay: true
      Bandwidth:
        Ref: CenBandwidth
      GeographicRegionAId: China
      GeographicRegionBId:
        Ref: CenGeographicRegionBId
      Period: 1
      PricingCycle:
        Ref: CenPricingCycle
    DependsOn:
    - CenBandwidthPackageAssociation1
  CenBandwidthPackageAssociation2:
    Type: ALIYUN::CEN::CenBandwidthPackageAssociation
    Condition: IsCreateOversea
    Properties:
      CenBandwidthPackageId:
        Ref: CenBandwidthPackage2
      CenId:
        Ref: CenInstance
    DependsOn:
    - CenBandwidthPackage2
    - CenInstance
  CenBandwidthLimit1:
    Type: ALIYUN::CEN::CenBandwidthLimit
    Condition: IsCreateOversea
    Properties:
      BandwidthLimit: 1
      CenId:
        Ref: CenInstance
      LocalRegionId:
        Ref: ChildInstanceRegionId2
      OppositeRegionId:
        Ref: ChildInstanceRegionId1
    DependsOn:
    - CenBandwidthPackageAssociation1
    - CenBandwidthPackageAssociation2
  CenBandwidthLimit2:
    Type: ALIYUN::CEN::CenBandwidthLimit
    Condition: IsCreateOversea
    Properties:
      BandwidthLimit: 1
      CenId:
        Ref: CenInstance
      LocalRegionId:
        Ref: ChildInstanceRegionId3
      OppositeRegionId:
        Ref: ChildInstanceRegionId1
    DependsOn:
    - CenBandwidthLimit1
    - CenBandwidthPackageAssociation1
    - CenBandwidthPackageAssociation2
  CenBandwidthLimit3:
    Type: ALIYUN::CEN::CenBandwidthLimit
    Properties:
      BandwidthLimit: 1
      CenId:
        Ref: CenInstance
      LocalRegionId:
        Ref: ChildInstanceRegionId3
      OppositeRegionId:
        Ref: ChildInstanceRegionId2
    DependsOn:
    - CenBandwidthLimit2
    - CenBandwidthPackageAssociation1
    - CenBandwidthPackageAssociation2
  CenBandwidthLimit4:
    Type: ALIYUN::CEN::CenBandwidthLimit
    Condition: IsCreateDomestic
    Properties:
      BandwidthLimit: 1
      CenId:
        Ref: CenInstance
      LocalRegionId:
        Ref: ChildInstanceRegionId2
      OppositeRegionId:
        Ref: ChildInstanceRegionId1
    DependsOn:
    - CenBandwidthLimit3
    - CenBandwidthPackageAssociation1
    - CenBandwidthPackageAssociation2
Outputs:
  CenId:
    Description:
      en: The ID of the cloud enterprise network instance
      zh-cn: 云企业网实例的ID。
    Value:
      Fn::GetAtt:
      - CenInstance
      - CenId
Metadata:
  ALIYUN::ROS::Interface:
    ParameterGroups:
    - Parameters:
      - ChildInstanceRegionId1
      - VpcId1Overseas
      - ChildInstanceRegionId2
      - VpcId2Domestic
      - VbrId4Domestic
      - ChildInstanceRegionId3
      - VpcId3Domestic
      - CenGeographicRegionBId
      - CenPricingCycle
      - CenBandwidth
      Label:
        default: CEN
    TemplateTags:
    - acs:solution:网络组网:在线教育全球部署网络规划-组建全球地域网络
