ROSTemplateFormatVersion: '2015-09-01'
Description: Test Waf DomainConfig、AclRule、WafSwitch
Parameters:
  Domain:
    Type: String
    Description: Domain name.
  InstanceId:
    Type: String
    Description: WAF instance ID. Description Interface You can view your current
      WAF instance ID by calling DescribePayInfo.
  Protocols:
    Type: String
    Description: 'The domain supports access protocols, values: http: expressed support
      for the HTTP protocol. https: support for HTTPS protocol. http, https: supports
      HTTP, HTTPS protocol.'
    Default: http
  ServiceOn:
    Type: Number
    Default: 1
  Region:
    Type: String
    Default: cn
  Rules:
    Type: String
    Default: '{"conditions":[{"key":"URL","contain":1,"value":"asfas"}],"continueComponent":{"post_action_cc":1,"post_action_waf":1,"post_action_sa":1,"post_action_block_geo":"0","post_action_data_risk_control":"1"},"action":"1","name":"test"}'
Resources:
  DomainConfig:
    Type: ALIYUN::WAF::DomainConfig
    Properties:
      InstanceId:
        Ref: InstanceId
      Domain:
        Ref: Domain
      SourceIps: '["1.1.1.1"]'
      HttpPort: '["80"]'
      IsAccessProduct: 0
      Protocols:
        Ref: Protocols
  WafSwitch:
    Type: ALIYUN::WAF::WafSwitch
    Properties:
      InstanceId:
        Ref: InstanceId
      Domain:
        Ref: Domain
      ServiceOn:
        Ref: ServiceOn
      Region:
        Ref: Region
    DependsOn: DomainConfig
  AclRule:
    Type: ALIYUN::WAF::AclRule
    Properties:
      InstanceId:
        Ref: InstanceId
      Rules:
        Ref: Rules
      Domain:
        Ref: Domain
      Region:
        Ref: Region
    DependsOn: WafSwitch
Outputs:
  ProtocolType:
    Description: 'agreement type:0: indicates that the HTTP protocol is supported.1:
      indicates that the HTTPS protocol is supported.2: indicates that both HTTP and
      HTTPS protocols are supported.'
    Value:
      Fn::GetAtt:
      - DomainConfig
      - ProtocolType
  Cname:
    Description: CNAME assigned by WAF instance.
    Value:
      Fn::GetAtt:
      - DomainConfig
      - Cname
